// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-southeast-2",
    "aws_cognito_identity_pool_id": "ap-southeast-2:9bf3e83d-8029-4d99-8638-91ebd42e25f4",
    "aws_cognito_region": "ap-southeast-2",
    "aws_user_pools_id": "ap-southeast-2_0W2zr47F7",
    "aws_user_pools_web_client_id": "1skmbdpvjteg6gq5ob5bomcn9e",
    "oauth": {}
};


export default awsmobile;
